# Generated by Django 3.2.9 on 2021-11-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='discord',
            field=models.URLField(default='', verbose_name='Дискорд'),
        ),
    ]
