# Generated by Django 3.2.9 on 2021-11-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0012_auto_20211125_0937'),
        ('Account', '0003_alter_user_discord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='game_modes',
            field=models.ManyToManyField(related_name='Режимы', to='Game.GameMode'),
        ),
    ]
