# Generated by Django 3.2.9 on 2021-12-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_user_game_modes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cs_rank',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Звание в MM'),
        ),
        migrations.AlterField(
            model_name='user',
            name='teams',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Участники команды (если вы принимаете участие в нескольких командных играх, указать состав для каждой дисциплины)'),
        ),
    ]
