# Generated by Django 3.2.9 on 2021-12-26 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_auto_20211203_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='cs_rank',
        ),
        migrations.RemoveField(
            model_name='user',
            name='discord',
        ),
        migrations.RemoveField(
            model_name='user',
            name='teams',
        ),
    ]
