# Generated by Django 3.2.9 on 2021-11-18 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('map', models.CharField(max_length=50, verbose_name='Map')),
                ('score', models.CharField(max_length=10, verbose_name='Score')),
                ('link_demo', models.URLField(verbose_name='Link to the demo game')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Game mode',
                'verbose_name_plural': 'Game modes',
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=50, verbose_name='Team')),
                ('kills', models.PositiveSmallIntegerField(default=0, verbose_name='Kills')),
                ('deaths', models.PositiveSmallIntegerField(default=0, verbose_name='Deaths')),
                ('assists', models.PositiveSmallIntegerField(default=0, verbose_name='Assists')),
                ('kd', models.PositiveSmallIntegerField(default=0, verbose_name='K/D')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Game.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserStats',
                'verbose_name_plural': 'UserStats',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='game_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.gamemode'),
        ),
    ]
