# Generated by Django 3.2.9 on 2021-11-20 20:01

import Game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='assists',
            field=models.FloatField(default=0, verbose_name='Assists'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='kd',
            field=models.PositiveSmallIntegerField(default=Game.models.UserStats.count_kd, verbose_name='K/D'),
        ),
    ]
