# Generated by Django 3.2.9 on 2021-11-21 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0003_auto_20211120_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='kd',
        ),
    ]
