# Generated by Django 3.2.9 on 2021-11-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0004_remove_userstats_kd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='score',
        ),
        migrations.AddField(
            model_name='game',
            name='team1_score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Team 1 score'),
        ),
        migrations.AddField(
            model_name='game',
            name='team2_score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Team 2 score'),
        ),
    ]
