# Generated by Django 3.2.9 on 2021-11-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0005_auto_20211121_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='team1_status',
            field=models.CharField(choices=[('win', 'loss'), ('win', 'loss')], default='', max_length=4, verbose_name='Team 1 status'),
        ),
        migrations.AddField(
            model_name='game',
            name='team2_status',
            field=models.CharField(choices=[('win', 'loss'), ('win', 'loss')], default='', max_length=4, verbose_name='Team 2 status'),
        ),
    ]
