# Generated by Django 3.2.9 on 2021-11-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0006_auto_20211121_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='team1_status',
        ),
        migrations.RemoveField(
            model_name='game',
            name='team2_status',
        ),
        migrations.AddField(
            model_name='userstats',
            name='team_status',
            field=models.CharField(choices=[('win', 'loss'), ('win', 'loss')], default='', max_length=4, verbose_name='Team status'),
        ),
    ]
