# Generated by Django 3.2.9 on 2021-11-22 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0007_auto_20211122_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='game',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='team',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='team_status',
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Team name')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='Team score')),
                ('is_winner', models.BooleanField(default=False, verbose_name='Is team a winner')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.game')),
            ],
        ),
    ]
