# Generated by Django 3.2.9 on 2021-11-22 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0009_userstats_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='team1_score',
        ),
        migrations.RemoveField(
            model_name='game',
            name='team2_score',
        ),
    ]
