# Generated by Django 3.2.9 on 2021-11-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0010_auto_20211122_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='link_demo',
            field=models.URLField(null=True, verbose_name='Link to the demo game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='map',
            field=models.CharField(max_length=50, null=True, verbose_name='Map'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='assists',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Помощи'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='deaths',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Смерти'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='kills',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Убийства'),
        ),
    ]
