# Generated by Django 3.2.9 on 2021-11-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0012_auto_20211125_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='assists',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Помощи'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='deaths',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Смерти'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='kills',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Убийства'),
        ),
    ]
