# Generated by Django 3.2.9 on 2021-11-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0013_auto_20211125_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='link_demo',
            field=models.URLField(blank=True, verbose_name='Link to the demo game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='map',
            field=models.CharField(blank=True, max_length=50, verbose_name='Map'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='assists',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Помощи'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='deaths',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Смерти'),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='kills',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Убийства'),
        ),
    ]
